apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysqldump
spec:
  schedule: 30 13 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysqldump
            image: koollman/mysqldump
            env:
              - name: ALL_DATABASES
                valueFrom:
                  configMapKeyRef:
                    name: mysqldump
                    key: all_databases
              - name: DB_HOSTS
                valueFrom:
                  configMapKeyRef:
                    name: mysqldump
                    key: dbhosts
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: mysqldump
                    key: dbuser
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    name: mysqldump
                    key: dbpass
              - name: TARGET_HOST
                valueFrom:
                  configMapKeyRef:
                    name: transporter
                    key: target.host
              - name: TARGET_PATH
                valueFrom:
                  configMapKeyRef:
                    name: transporter
                    key: target.path
              - name: LINUX_USER
                valueFrom:
                  configMapKeyRef:
                    name: transporter
                    key: linux.user
            volumeMounts:
              - mountPath: /mysqldump
                name: mysqldump
              - mountPath: /root/.ssh/private
                name: transporter-key
          volumes:
            - name: mysqldump
              emptyDir: {}
            - name: transporter-key
              secret:
                secretName: transporter-key
                defaultMode: 256
          restartPolicy: OnFailure
